name: Integration tests

on:
  pull_request:
    branches:
     - master
  push:
    branches:
      - master

jobs:
  tests:
    name: test ${{ matrix.event_loop_manager }} (${{ matrix.python-version }})
    if: "!contains(github.event.pull_request.labels.*.name, 'disable-integration-tests')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.17", "3.11.4", "3.12.0b4"]
        event_loop_manager: ["libev", "asyncio", "asyncore"]
        exclude:
          - python-version: "3.12.0b4"
            event_loop_manager: "asyncore"

    steps:
    - uses: actions/checkout@v3
    - name: setup pyenv ${{ matrix.python-version }}
      uses: "gabrielfalcao/pyenv-action@v16"
      with:
        default: 2.7.14
        versions: ${{ matrix.python-version }}
    - name: Test with pytest
      run: |
        export EVENT_LOOP_MANAGER=${{ matrix.event_loop_manager }}
        export SCYLLA_VERSION='release:5.1'
        ./ci/run_integration_test.sh tests/integration/standard/test_metrics.py
    
    - name: Test tablets
      run: |
        export EVENT_LOOP_MANAGER=${{ matrix.event_loop_manager }}
        export SCYLLA_VERSION='unstable/master:2024-01-17T17:56:00Z'
        ./ci/run_integration_test.sh tests/integration/experiments/
